title:              Runit Misra
email:              misra.runit@gmail.com 
description:        A Website about me and a place for me to write about things I care about 
author:             Runit Misra 
baseurl:            ""
url:                "https://runitmisra.github.io"

# Social Profiles
twitter_username:   
github_username:    runitmisra
facebook_username:  
instagram_username:  
linkedin_username:  runit-misra

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-midnight